<?php
/**
 * WPFactory theme - Carbon Fields Data store.
 *
 * @version 1.0.0
 * @since   1.0.0
 * @author  WPFactory
 */

namespace WPFactory\WPFactory_Theme\Carbon_Fields;

use \Carbon_Fields\Container;
use Carbon_Fields\Datastore\Theme_Options_Datastore;
use \Carbon_Fields\Field;
use \Carbon_Fields\Datastore\Post_Meta_Datastore;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
} // Exit if accessed directly

if ( ! class_exists( 'WPFactory\WPFactory_Theme\Carbon_Fields\Carbon_Fields_Theme_Options_Datastore' ) ) {

	class Carbon_Fields_Theme_Options_Datastore extends Theme_Options_Datastore {
		//save_key_value_pair

		protected $field;

		public function save( \Carbon_Fields\Field\Field $field ) {
			$this->field = $field;
			parent::save( $field ); // TODO: Change the autogenerated stub
		}

		protected function save_key_value_pair_with_autoload( $key, $value, $autoload = true ) {
			$value = Carbon_Fields_Sanitizing::sanitize_field( $this->field, $value );
			parent::save_key_value_pair_with_autoload( $key, $value, $autoload ); // TODO: Change the autogenerated stub
		}

		function save_key_value_pair( $key, $value ) {
			$value = Carbon_Fields_Sanitizing::sanitize_field( $this->field, $value );
			parent::save_key_value_pair( $key, $value ); // TODO: Change the autogenerated stub
		}

	}
}